'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { addEdge, applyEdgeChanges, applyNodeChanges, Background, Controls, MiniMap, ReactFlow, useEdgesState, useNodesState, type Connection, type Edge, type Node, type NodeChange, type EdgeChange } from '@xyflow/react';
import { Archive, ArrowRight, BookOpen, CalendarDays, Check, CirclePlus, Download, FileText, GitBranch, Lightbulb, Plus, Search, StickyNote, Trash2, Wallet, X } from 'lucide-react';

type Idea = { id:string; text:string; created:string };
type Target = { id:string; title:string; from:string; to:string; notes:string; done:boolean };
type Graph = { id:string; name:string; purpose:string; nodes:Node[]; edges:Edge[]; updated:string };
const STORE='orbit-v3-local-data';
const colors=['#fff0b3','#dff4e7','#e4eaff','#ffe4e7','#f6e4ff','#e2f4f7'];
const starterGraphs:Graph[]=[];
function newId(){return Math.random().toString(36).slice(2,10)}
function IdeaNode({data,selected}:{data:any;selected?:boolean}) { return <div className={'sketch-node '+(selected?'selected':'')} style={{background:data.color||'#fff0b3'}}><div className="node-title">{data.label}</div>{data.detail&&<div className="node-detail">{data.detail}</div>}<div className="handle handle-left"/><div className="handle handle-right"/><div className="handle handle-top"/><div className="handle handle-bottom"/></div> }
const nodeTypes={idea:IdeaNode};
export default function Workspace(){
 const [ready,setReady]=useState(false); const [tab,setTab]=useState<'graphs'|'ideas'|'planning'>('graphs');
 const [graphs,setGraphs]=useState<Graph[]>([]); const [activeId,setActiveId]=useState(''); const [ideas,setIdeas]=useState<Idea[]>([]); const [targets,setTargets]=useState<Target[]>([]);
 const [ideaText,setIdeaText]=useState(''); const [search,setSearch]=useState(''); const [graphName,setGraphName]=useState(''); const [showNewGraph,setShowNewGraph]=useState(false);
 const [targetTitle,setTargetTitle]=useState(''); const [targetFrom,setTargetFrom]=useState(new Date().toISOString().slice(0,10)); const [targetTo,setTargetTo]=useState(new Date().toISOString().slice(0,10)); const [targetNotes,setTargetNotes]=useState('');
 const [nodeLabel,setNodeLabel]=useState(''); const [nodeDetail,setNodeDetail]=useState(''); const [edgeLabel,setEdgeLabel]=useState(''); const [selectedNode,setSelectedNode]=useState('');
 useEffect(()=>{try{const raw=localStorage.getItem(STORE); if(raw){const d=JSON.parse(raw);setGraphs(d.graphs||starterGraphs);setIdeas(d.ideas||[]);setTargets(d.targets||[]);setActiveId(d.activeId||(d.graphs?.[0]?.id)||starterGraphs[0]?.id||'');}else{setGraphs(starterGraphs);setActiveId(starterGraphs[0]?.id||'')}}catch{setGraphs(starterGraphs);setActiveId(starterGraphs[0]?.id||'')}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(STORE,JSON.stringify({graphs,ideas,targets,activeId}))},[ready,graphs,ideas,targets,activeId]);
 const active=graphs.find(g=>g.id===activeId)||graphs[0];
 const [nodes,setNodes,onNodesChange]=useNodesState<Node>([]); const [edges,setEdges,onEdgesChange]=useEdgesState<Edge>([]);
 useEffect(()=>{if(active){setNodes(active.nodes||[]);setEdges(active.edges||[])}else{setNodes([]);setEdges([])}},[activeId,ready]);
 const syncGraph=useCallback((nextNodes:Node[],nextEdges:Edge[])=>{setGraphs(prev=>prev.map(g=>g.id===activeId?{...g,nodes:nextNodes,edges:nextEdges,updated:new Date().toISOString()}:g))},[activeId]);
 const handleNodesChange=useCallback((changes:NodeChange<Node>[])=>{setNodes(current=>{const next=applyNodeChanges(changes,current);syncGraph(next,edges);return next})},[setNodes,syncGraph,edges]);
 const handleEdgesChange=useCallback((changes:EdgeChange<Edge>[])=>{setEdges(current=>{const next=applyEdgeChanges(changes,current);syncGraph(nodes,next);return next})},[setEdges,syncGraph,nodes]);
 const onConnect=useCallback((connection:Connection)=>{setEdges(eds=>{const next=addEdge({...connection,label:edgeLabel||undefined,type:'smoothstep',animated:false,style:{stroke:'#42403c',strokeWidth:1.8},labelStyle:{fill:'#48453f',fontSize:12}},eds);syncGraph(nodes,next);return next});setEdgeLabel('')},[setEdges,nodes,syncGraph,edgeLabel]);
 const addNode=()=>{if(!active||!nodeLabel.trim())return;const id=newId();const n:Node={id,type:'idea',position:{x:100+Math.random()*260,y:100+Math.random()*260},data:{label:nodeLabel.trim(),detail:nodeDetail.trim(),color:colors[nodes.length%colors.length]}};const next=[...nodes,n];setNodes(next);syncGraph(next,edges);setNodeLabel('');setNodeDetail('')};
 const createGraph=()=>{if(!graphName.trim())return;const g:Graph={id:newId(),name:graphName.trim(),purpose:'',nodes:[],edges:[],updated:new Date().toISOString()};setGraphs(p=>[...p,g]);setActiveId(g.id);setGraphName('');setShowNewGraph(false);setTab('graphs')};
 const deleteGraph=()=>{if(!active||!confirm(`Delete graph “${active.name}”? This cannot be undone.`))return;const rest=graphs.filter(g=>g.id!==active.id);setGraphs(rest);setActiveId(rest[0]?.id||'');};
 const captureIdea=()=>{if(!ideaText.trim())return;setIdeas(p=>[{id:newId(),text:ideaText.trim(),created:new Date().toISOString()},...p]);setIdeaText('')};
 const promoteIdea=(idea:Idea)=>{setNodeLabel(idea.text);setTab('graphs');setIdeas(p=>p.filter(i=>i.id!==idea.id))};
 const addTarget=()=>{if(!targetTitle.trim())return;setTargets(p=>[{id:newId(),title:targetTitle.trim(),from:targetFrom,to:targetTo,notes:targetNotes,done:false},...p]);setTargetTitle('');setTargetNotes('')};
 const filteredIdeas=ideas.filter(i=>i.text.toLowerCase().includes(search.toLowerCase()));
 if(!ready)return <div className="loading">Opening your local workspace…</div>;
 return <main className="app-shell">
  <aside className="rail"><div className="brand-mark">O</div><div className="rail-rule"/><button className={tab==='graphs'?'rail-button active':'rail-button'} title="Graphs" onClick={()=>setTab('graphs')}><GitBranch size={20}/></button><button className={tab==='ideas'?'rail-button active':'rail-button'} title="Idea inbox" onClick={()=>setTab('ideas')}><Lightbulb size={20}/>{ideas.length>0&&<span className="count-dot"/>}</button><button className={tab==='planning'?'rail-button active':'rail-button'} title="Planning" onClick={()=>setTab('planning')}><CalendarDays size={20}/></button><div className="rail-spacer"/><div className="local-chip" title="Saved on this device"><Archive size={15}/><span>LOCAL</span></div></aside>
  <section className="main-area"><header className="topbar"><div><div className="eyebrow">PERSONAL THINKING SPACE · V3</div><h1>{tab==='graphs'?'Graph studio':tab==='ideas'?'Idea inbox':'Planning board'}</h1></div><div className="top-actions"><span className="save-status"><span className="save-dot"/> Saved on this device</span>{tab==='graphs'&&<button className="primary-btn" onClick={()=>setShowNewGraph(true)}><Plus size={16}/> New graph</button>}</div></header>
  {tab==='graphs'&&<div className="studio"><aside className="graph-sidebar"><div className="side-heading"><span>YOUR GRAPHS</span><button className="icon-button" onClick={()=>setShowNewGraph(true)} title="Create graph"><Plus size={16}/></button></div><div className="graph-list">{graphs.length===0&&<p className="no-graphs">No graphs yet. Create one to start mapping ideas.</p>}{graphs.map(g=><button key={g.id} className={'graph-list-item '+(g.id===activeId?'selected':'')} onClick={()=>setActiveId(g.id)}><span className="graph-icon"><GitBranch size={15}/></span><span className="graph-item-copy"><strong>{g.name}</strong><small>{g.nodes.length} nodes · {g.edges.length} links</small></span><ArrowRight size={14} className="list-arrow"/></button>)}</div><div className="sidebar-note"><Lightbulb size={16}/><p>Make a separate graph for each system: learning, money, decisions, habits or causal relationships.</p></div><div className="quick-add"><div className="side-heading"><span>ADD A NODE</span></div><label>Label</label><input value={nodeLabel} onChange={e=>setNodeLabel(e.target.value)} placeholder="e.g. Monthly savings" onKeyDown={e=>e.key==='Enter'&&addNode()}/><label>Detail (optional)</label><textarea value={nodeDetail} onChange={e=>setNodeDetail(e.target.value)} placeholder="Context, evidence, questions…" rows={2}/><button className="primary-btn full" onClick={addNode}><CirclePlus size={16}/> Add to canvas</button><p className="microcopy">Drag nodes to arrange. Connect the small handles to show relationships.</p></div></aside>
  <div className="canvas-column"><div className="canvas-toolbar"><div className="canvas-title"><strong>{active?.name||'No graph selected'}</strong><span>{active?.purpose||'Freeform map · connect ideas and causes'}</span></div><div className="canvas-actions"><span className="tiny-pill">{nodes.length} nodes</span><span className="tiny-pill">{edges.length} links</span><button className="icon-button" title="Delete this graph" onClick={deleteGraph}><Trash2 size={16}/></button></div></div><div className="canvas-wrap"><div className="canvas-watermark">SKETCH SPACE <span>·</span> DRAG TO ARRANGE</div>{!active&&<div className="empty-canvas"><GitBranch size={28}/><strong>Create your first graph</strong><p>Choose New graph to create an empty canvas for any topic.</p><button className="primary-btn" onClick={()=>setShowNewGraph(true)}><Plus size={15}/> New graph</button></div>}<ReactFlow nodes={nodes} edges={edges} onNodesChange={handleNodesChange} onEdgesChange={handleEdgesChange} onConnect={onConnect} onNodeClick={(_,n)=>setSelectedNode(n.id)} nodeTypes={nodeTypes} fitView defaultEdgeOptions={{type:'smoothstep',style:{stroke:'#42403c',strokeWidth:1.8}}} proOptions={{hideAttribution:true}}><Background variant={'dots' as any} gap={22} size={1} color="#d9d5cc"/><MiniMap pannable zoomable nodeColor={(n:any)=>n.data?.color||'#fff0b3'}/><Controls/></ReactFlow>{nodes.length===0&&<div className="empty-canvas"><GitBranch size={28}/><strong>Start with one important idea</strong><p>Add a node from the left, then connect it to other concepts.</p></div>}</div><div className="canvas-footer"><span><span className="keycap">SPACE</span> + drag to pan</span><span><span className="keycap">SCROLL</span> to zoom</span><span>Connections can be labelled before linking</span></div></div></div>}
  {tab==='ideas'&&<section className="ideas-page"><div className="ideas-intro"><div className="intro-icon"><Lightbulb size={24}/></div><div><h2>Capture now. Organize later.</h2><p>A low-friction inbox for unfinished thoughts. Promote an idea into the graph you are working on when it becomes useful.</p></div></div><div className="capture-card"><textarea value={ideaText} onChange={e=>setIdeaText(e.target.value)} placeholder="An idea, question, observation, possible experiment…" rows={3}/><div className="capture-bottom"><span>Ideas are stored locally in this browser profile.</span><button className="primary-btn" onClick={captureIdea}><Plus size={16}/> Capture idea</button></div></div><div className="list-toolbar"><h3>Inbox <span className="subcount">{ideas.length}</span></h3><div className="searchbox"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search ideas"/></div></div>{filteredIdeas.length===0?<div className="empty-state"><StickyNote size={28}/><strong>{ideas.length?'No matching ideas':'Your inbox is clear'}</strong><p>{ideas.length?'Try a different search.':'Capture thoughts here without interrupting your current work.'}</p></div>:<div className="idea-grid">{filteredIdeas.map(i=><article className="idea-card" key={i.id}><div className="idea-card-top"><span className="idea-label"><StickyNote size={14}/> QUICK NOTE</span><button className="icon-button" onClick={()=>setIdeas(p=>p.filter(x=>x.id!==i.id))} title="Delete idea"><Trash2 size={15}/></button></div><p>{i.text}</p><div className="idea-card-bottom"><small>{new Date(i.created).toLocaleDateString()}</small><button className="text-btn" onClick={()=>promoteIdea(i)}>Move to graph <ArrowRight size={14}/></button></div></article>)}</div>}</section>}
  {tab==='planning'&&<section className="planning-page"><div className="planning-intro"><div><h2>Planning board</h2><p>Define outcomes with a date range. Keep plans lightweight and connect them to a graph when you need to reason about them.</p></div></div><div className="target-form"><div className="form-heading"><CalendarDays size={18}/><strong>Add a target</strong></div><input className="wide-input" value={targetTitle} onChange={e=>setTargetTitle(e.target.value)} placeholder="What do you want to accomplish?"/><div className="date-row"><label>From<input type="date" value={targetFrom} onChange={e=>setTargetFrom(e.target.value)}/></label><label>To<input type="date" min={targetFrom} value={targetTo} onChange={e=>setTargetTo(e.target.value)}/></label></div><textarea value={targetNotes} onChange={e=>setTargetNotes(e.target.value)} rows={2} placeholder="Notes (optional)"/><button className="primary-btn" onClick={addTarget}><Plus size={16}/> Add target</button></div><div className="list-toolbar"><h3>Targets <span className="subcount">{targets.length}</span></h3></div>{targets.length===0?<div className="empty-state"><CalendarDays size={28}/><strong>No targets yet</strong><p>Add a target with a start and end date. Nothing is preloaded.</p></div>:<div className="target-list">{targets.map(t=><article key={t.id} className={'target-card '+(t.done?'is-done':'')}><button className="check-target" onClick={()=>setTargets(p=>p.map(x=>x.id===t.id?{...x,done:!x.done}:x))} title="Toggle completion">{t.done&&<Check size={15}/>}</button><div className="target-copy"><strong>{t.title}</strong><span>{t.from===t.to?t.from:`${t.from} → ${t.to}`}</span>{t.notes&&<p>{t.notes}</p>}</div><button className="icon-button" onClick={()=>setTargets(p=>p.filter(x=>x.id!==t.id))} title="Delete target"><Trash2 size={15}/></button></article>)}</div>}</section>}
  <footer className="app-footer"><span>ORBIT V3</span><span>Local-first · No account · No cloud sync</span><span>Data stays in this browser unless you clear site data.</span></footer></section>
  {showNewGraph&&<div className="modal-backdrop" onClick={()=>setShowNewGraph(false)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">GRAPH STUDIO</span><h2>Create a graph</h2></div><button className="icon-button" onClick={()=>setShowNewGraph(false)}><X size={18}/></button></div><p>Give each graph a specific purpose. Start empty and build only what you need.</p><label>Graph name</label><input autoFocus value={graphName} onChange={e=>setGraphName(e.target.value)} placeholder="e.g. Personal cash flow" onKeyDown={e=>e.key==='Enter'&&createGraph()}/><div className="suggestions"><button onClick={()=>setGraphName('Personal cash flow')}><Wallet size={15}/> Personal cash flow</button><button onClick={()=>setGraphName('Learning memory map')}><BookOpen size={15}/> Learning memory map</button><button onClick={()=>setGraphName('Decision analysis')}><GitBranch size={15}/> Decision analysis</button></div><div className="modal-actions"><button className="secondary-btn" onClick={()=>setShowNewGraph(false)}>Cancel</button><button className="primary-btn" onClick={createGraph}><Plus size={16}/> Create empty graph</button></div></div></div>}
 </main>
}
